default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  host: 127.0.0.1
  port: 3306
  database: pchatter_test

production:
  <<: *default
  socket: <%= ENV["DB_SOCKET"] %>
